sudo: false
language: node_js
node_js: 8

cache:
  directories:
    - node_modules
    - .travis-tmp/node_modules

script:
  - npm test
  - mkdir .travis-tmp
  - cd .travis-tmp
  - node ../test/util/install-app-4.js
  - npm install
  - npm run build:demo:aot
  - npm test
  - cd ..

after_success: "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
