sudo: false
language: node_js
node_js: 8

cache:
  directories:
    - node_modules
    - ".travis-tmp/node_modules"

script:
  - npm test
  - node mkdir-travis-tmp.js
  - bash -c "cd .travis-tmp && node ../test/util/install-app-4.js && npm install && npm run build:demo:aot && npm test"

after_success: "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"

before_deploy:
  - npm run build:prod
  - npm pack

before_cache: rm -rf node_modules/.cache

deploy:
  - provider: npm
    skip_cleanup: true
    email: a.molcanovas@gmail.com
    on:
      tags: true
    api_key:
      secure: FHG0LjP6QIfQoxCKFiCV+sUjkHei5/IdpWN13TzM/QmWkB9MGNxkpRXGbjmPal/aGTRhdo3jhpRBrQZs3nm3l2WcVy/YwiTSjU3ryJYCxJHYve3xKQbfn/IBvj2dc19hlot/L5VHp/aJGJTWb7yEcBVKbRgpiOIOEFo6EMaIivwRI2Ev86hg7rSSz6PWvBCQFdOvt2uaTepI88dxAIcFpF0vrY9RpmbHaoYZrHwm0HZmlv61U0DtOkVA0aFTGyFeB2TCmDu3HGPgDfs3dtAl0F4d0HwmVbZebe4ke1sNF3N7ealhVs3i7zBqElkKaUkzid3wY53Rj0Pp0db4NMNe+TGRZ/Poj5oart20k1+xepRrI6Op/MjRz2LKHx/D99Yv1h5dE8umubnkzIsCB1T/ts6ZeHjZLVn9OJgIqMfxZq4PH8cYpdoKYkbSKjGGzhgGeQ4NH+1me/JTSR/IzRkS1oS3q3K0oIVoPWXS2wZZ52jfufIhK2so8t+vg9Ld7SvTb7wb5kKgrWFIy162y5Twa3nD/ElMa9CVIBG233fz7ZQe6b/bTcClXp5/CT2SDzmm1m1U8VQTq2pA5yo/BVb70SS7g5doDwLT/Nc9/+1Qs3bUkHAH3io+DfHVb5oQ8CjC3Xn6XQWoOMVAMBoE+n5o7NnhLT8i0wCVHgaCzfA7Uvg=
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: "*.tgz"
    on:
      tags: true
    api_key:
      secure: J9F+VhgpzAnIKM8IS41ycj3TdtswNZtAOn2BvZu0KCJbUEJt+dsv9foJpdmGO3JH1vDPD68PBRwtUPB29aCNVmHHuSy9631/P9D/KGjAMqroB7rniOK2PLZOvNUKu5jCCxAMVWku4qfqgC7f0WmKIR3q9n+WUdUBPd87LDma7Wy63s2SVFOoOsmYdcNhfF1+mI/6qEjghF04+f0e4X7l6Bj86khZpyGqrirIPuQblQB7KbdFbqqYaGPEaUX4MuhPKrB0A64prA1YRQGynd/y8qXQOF2iWMCI1ZJg8IjTmKnJrwAxI0tuftMhdXh6iezGD54kF0RSpEO+FbM524utYP2qAfRUd/KunhmLZYxxcu/2+5RVewXsUrRhTXzFlfwefWklUWaTIpG76C2iR+5+kXGbhoevC0hO/J4tzIeFsZVFKtT8mY6eOxPOf3X3HZA1aD7TKcb5JZda8uDhScyP/UUcmpxSOPHL34sjBOZ/WNpywoUPEqLeV0c240AJxY6qwCSMecv2PKAKsrkSm19Gwkj6BlZiA6/eDo9/LgD+Ryc1FB4x92y2R8Zk+R7+ily2PrwELjSoCZ/z/ebkAkwSC+Qbse8jNprt7wwsdM9hLhYfgpPMgg/lVaj6sJvXppQlekfQe3pgsYcro/lILVp7sVNJYxjT7rm2ugP4KcY7eYk=
