sudo: false
language: node_js

generator: &generator
  stage: test generator
  env:
    - CACHE_KEY=root-only
  cache:
    directories:
      - node_modules
  before_script: greenkeeper-lockfile-update
  before_cache: rm -rf node_modules/.cache
  script:
    - npm test
    - npm run lint
    - if [ $SNYK_TOKEN ]; then snyk test --dev; fi;
  after_success:
    - cat ./coverage/lcov.info | coveralls

latest_node_version_used: &latest_node_version_used 9

env:
  global:
    # GH
    - secure: X3Op4kF+X34JVZldxKORn1xctJ7gmc5/AReKmq1+rYcydaeUIyZjm5x1daeWoqTDuflc8/+pNhCFBM6poDyCtmbVy8fNs+zcX0kg0aQhbMGcJQYh9PHww1ek1HHKiPE0P2Ll05eKQS2fxtI9U78Jd+76+SI5k40m9YzqPB2mGWsmcuPKxckObRfvhkDzYR7fzaE/6Ur6zv9BhXTMW5lDFvtkmDrhvInfj5UmzpAzinrf75XJjr528mqdC2ct0y+GQkCO4fa447Gj1n5ohr20eQrUU1V0nvb3gbkcnIMhwq5EOSCdotL3tFGBpgtNp/VQ2BLZXWodwXjxsKVurtWFAkToLiOsmDnG0ylmwgaubhyd8wqH4fOom325LOiqhfx2bKiy//MGK6eiBrQu4EHcZvRbXfqJsQvTqMo39hBRsVKyI2VbdXae53GaN3JNRzx9sQLOjlkNSqQ7IXE6yJKG0hmoXMSRrWmnZsqoOUiKSQ9RhYLWMatSh+vLSGm9ysgO1PBIUYa7KnsD2krCUeWMCeL95n3b7kTFlQBDawnjt4nK+/9S1MWUp3d57gRxqvURoPa3jR1jpkENeLfw1mKFPbUMDoXgsylHE3nmPihk6LAqckvAbvKUr65XsAJVfVB+gky0FzAKEq8oqhM3zxlwSAgJCwNKtibZc764OIzaG9Y=
    # Snyk
    - secure: wAF0/E+fnikLd4ReLypMUOpGMv0dM4zC4ydEugCNCOXuHaTLhCMmkAgcE8OgFdaG8PQNwvdFpQezoSN0Zs3TgFlaX/WK/qK+lhKZU/thOmhhfBxTVnfhty4fQ8H1yXRW+SQumRaY1NQ6cWvJJMzZKRESbEGhuBqpqBrddDvsukfh9fUGHdMI63P4lHbOPVPQcedpJDsJFR4w1TLKENzyRATYwiNMWRj+DxM2kNryhYoJ4WxUFVCh7zdQdtv8IKY3GpenvmWCkrSvzHQKu3SuC2Gca49WFN1J1wpdfy2+mjDutAVHMmTW3w1pnnwllWwTlEU6AGVBrMbQwpLe/TvcWx7kWWybKri1cQ5KPbOnVJ+DNvdVEcgGpg2PA0eWn7uayNT+Y6vadl/oeqs4UBHUXL8aunWve5GNGJhkCtI7s71SzMnQbYNIo/jKqVfyMjn0DDs7P67lHJX09jQsmJIhCGSTVNP11qoPdEx8kGi8mlMBxrvJh3zw2aplEjUaom3exq9zmXuq8C0B8RyhYrkF2YbA/iUErj3qSByNLRLL0FU2FCBuoqt7dfuoj3o+g9wuBLMYjuutyDvb2iwsFqeS7ao2kMrboalsETMiEKE/GguB5saN/dZaMyi3qJ3zY3Hkq0vp8m8NM95aB7Lri+/IgKxs71w7f0VcvZIvBc9MPt0=

stages:
  - test generator
  - name: deploy
    if: tag IS present

jobs:
  include:
    - <<: *generator
      node_js: 9
      after_script:
        - if [ $GH_TOKEN ]; then greenkeeper-lockfile-upload; fi;
        - if [ $SNYK_TOKEN ]; then snyk monitor --dev; fi;
    - stage: test generator
      node_js: *latest_node_version_used
      env:
        - CACHE_KEY=generated
      cache:
        directories:
          - node_modules
          - .travis-tmp/node_modules
      before_script:
        - greenkeeper-lockfile-update
        - tsc
      script:
        - mkdir -p .travis-tmp
        - bash -c "cd .travis-tmp && node ../test/util/install-app-4.js"
        - bash -c "cd .travis-tmp && npm install"
        - bash -c "cd .travis-tmp && npm run build:demo:aot"
        - bash -c "cd .travis-tmp && npm test"
      before_cache: rm -rf node_modules/.cache .travis-tmp/node_modules/.cache .travis-tmp/node_modules/puppeteer

    - stage: deploy
      node_js: *latest_node_version_used
      env:
        - CACHE_KEY=root-only
      cache:
        directories:
          - node_modules
      before_cache: rm -rf node_modules/.cache
      script: npm run build:prod
      deploy:
        - provider: npm
          skip_cleanup: true
          email: a.molcanovas@gmail.com
          on:
            tags: true
          api_key:
            secure: pL280LwIwMgZ4JsIVfEW9o943kOTnZXuGmlqJWNbaQbvpMPQ1TGYJoE0REp93q+HO8+0uNpLTwCkg9J3AlCQSmaRwaZSJfu0Q8n8uEmM2Dc1QBnBoAqa99RcHwO6Odz947H8OCXlUJg8az4CRcP+uqtSFIlWfrCDgd4hLVHd7hbHKVLSrI3J9WDHYEAmUT1jAp3GHHl4kQ/JIP9GPJ12B6W8H8okn2TRcbuiYwWdf7MGBGRkcaMeT+mf1tKHDdY/qXlXslMTvYc6m2k/eIrL7bHq5SdXcGAQbKxByG5dhAnSGSuf8esYMxJbrffHuIihl//ly8KEvR6pp3ACdhf7w/Tpf+mn0Jk5CpilYRIPhkiCxWCOxMQ3+v/Z5MsMI4vR5ZMwQxt7gAALG++sh8nK8coxSQ4+gGhMlCcjmPkgpkcYoQRMONxwB3+IXNsYwdXJNhCnjmMVGtb9NrxdjwjBTt08RLsrUjMVDe3XBmCIU1Rr+FKrWGFg+gtuizg3mvOPPEl8ftptfSkrmBHWzQbAuTirtuLNtX3Y7f7mENqSX2Sdiezv7+KadMsKndMTJJCWIX1wIfdMelMDT1r16XRGKCJzGTsjot7c9VI5AdvjkjR9gB3KiHbUojtLc/r4PTnOWH37QksSwY/Y0xOh2E+cMicv7GpvLWZxys/uP+NnU+Q=

    - <<: *generator
      node_js: 8
    - <<: *generator
      node_js: 7
